### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by ZBashev** [luchob/softuni-cars#1]
Здравейте ,закъсах го с моето Mobileleleeleeee . 
Изпратих ви покана ,ако може да погледнете.
Може би грешката е в UserDetailSecurityServices.

Благодаря предварително
Поздрави

**Comment by ZBashev** [comment]
махнах anyRequest().authenticated() и почти стана :) , но не ми покава логин формата

**Comment by luchob** [comment]
Ехе.... ами... има още доста да се желае, докато проработи :-) Най-малкото, не си му дал указания къде се намира логин формата, за да я покаже. Ето пример:

```
          // configure login with HTML form
          formLogin().
            // our login page will be served by the controller with mapping /users/login
            loginPage("/users/login").
            // the name of the user name input field in OUR login form is username (optional)
            usernameParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_USERNAME_KEY).
            // the name of the user password input field in OUR login form is password (optional)
            passwordParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_PASSWORD_KEY).
            // on login success redirect here
            defaultSuccessUrl("/home").
            // on login failure redirect here
            failureForwardUrl("/users/login-error")
```

Пълен пример има ето [тук](https://github.com/luchob/softuni-music-db/blob/master/src/main/java/bg/softuni/musicdb/config/ApplicationSecurityConfig.java#L39), обърни и внимание на коментарите в конфигурацията. Писани са за да ви улесняват.

Поздрави и успех,
Л.
